":octocat:":
  - changed-files:
    - any-glob-to-any-file: [".github/**/*"]

"Homepage":
  - changed-files:
    - any-glob-to-any-file: ["content/*"]

"Features":
  - changed-files:
    - any-glob-to-any-file: ["content/features/**"]

"Download":
  - changed-files:
    - any-glob-to-any-file: ["content/download/**"]

"News":
  - changed-files:
    - any-glob-to-any-file: ["content/news/**"]

"Community":
  - changed-files:
    - any-glob-to-any-file: ["content/community/**"]

"Documentation":
  - changed-files:
    - any-glob-to-any-file: ["content/docs/**"]

"Donate":
  - changed-files:
    - any-glob-to-any-file: ["content/donate/**"]

"Assets":
  - changed-files:
    - any-glob-to-any-file: ["assets/**"]

"Config":
  - changed-files:
    - any-glob-to-any-file: ["config/**"]

"Data":
  - changed-files:
    - any-glob-to-any-file: ["data/**"]

"Static":
  - changed-files:
    - any-glob-to-any-file: ["static/**"]

"Theme":
  - changed-files:
    - any-glob-to-any-file: ["themes/**"]

"English":
  - changed-files:
    - any-glob-to-any-file: ["content/**/*.en*.*"]

"中文":
  - changed-files:
    - any-glob-to-any-file: ["content/**/*.zh*.*"]

"Español":
  - changed-files:
    - any-glob-to-any-file: ["content/**/*.es*.*"]

"Français":
  - changed-files:
    - any-glob-to-any-file: ["content/**/*.fr*.*"]

"Português":
  - changed-files:
    - any-glob-to-any-file: ["content/**/*.pt*.*"]

"Deutsch":
  - changed-files:
    - any-glob-to-any-file: ["content/**/*.de*.*"]

"日本語":
  - changed-files:
    - any-glob-to-any-file: ["content/**/*.ja*.*"]

"русский":
  - changed-files:
    - any-glob-to-any-file: ["content/**/*.ru*.*"]

"Türkçe":
  - changed-files:
    - any-glob-to-any-file: ["content/**/*.tr*.*"]

"Italiano":
  - changed-files:
    - any-glob-to-any-file: ["content/**/*.it*.*"]

"Polski":
  - changed-files:
    - any-glob-to-any-file: ["content/**/*.pl*.*"]
